accounts/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views
from django.contrib.auth import views as auth_views



app_name = 'auth'

urlpatterns = [
    # path('', RedirectView.as_view(pattern_name='blog:feed', permanent=False), name='redirect-to-feed'),
    # path('feed/', views.FeedView.as_view(), name='feed'),
    # path('post/<int:pk>/', views.PostDetailsView.as_view(), name='post'),
    # path('user/<str:username>/', views.ProfileDetailsView.as_view(), name='user'),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path( "register/", views.RegisterView.as_view(), name='register'),
]

blog/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'blog'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='blog:feed', permanent=False), name='redirect-to-feed'),
    path('feed/', views.FeedView.as_view(), name='feed'),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('post/<int:pk>/', views.PostDetailsView.as_view(), name='post'),
    path('account/<str:username>/', views.ProfileDetailsView.as_view(), name='account'),
    path('account_settings/', views.AccountSettingsView.as_view(), name='account_settings'),
    path('delete_post/<int:pk>', login_required(views.delete_post), name="delete_post"),
    path('delete_comment/<int:pk>', login_required(views.delete_comment), name="delete_comment"),
    path('like_post_button/<int:pk>', login_required(views.like_post_button), name="like_post_button"),
    path('get_post_liked_status/<int:pk>', login_required(views.get_post_liked_status), name="get_post_liked_status"),
]

gatior/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('', lambda request: redirect(reverse_lazy("blog:feed"), permanent=True)),
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("auth/", include("accounts.urls")),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.conf import settings
from django.templatetags.static import static


class Account(AbstractUser):
    username_validator = RegexValidator(
        regex=r'^[a-zA-Z0-9._-]{4,}$',
        message=_('Username can only contain letters, numbers, dots, and underscores.')
    )

    email = models.EmailField(
        _("email address"),
        unique=True,
        blank=False,
        null=False,
        help_text=_('Required. Your email addres.'),
        error_messages={
            'unique': _("A user with that email already exists."),
        },
        )

    username = models.CharField(
        _('username'),
        max_length=20,
        unique=True,
        help_text=_('Required. Your personal identificator. 20 characters or fewer. Letters, numbers, dots, hyphenses and underscores only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    first_name = models.CharField(
        _("first name"),
        max_length=20,
        help_text=_('Required. Your first name you want to be known by.'),
    )
    
    last_name = models.CharField(
        _("last name"),
        max_length=20,
        blank=True,
        help_text=_('Optional. Your last name you want to be known by.'),
    )

    profile_picture = models.ImageField(
        _('profile picture'),
        upload_to='profile_pictures/%Y/%m/%d/',
        blank=True,
        null=True,
        default=None,
        help_text=_('Optional. Upload a profile picture.'),
    )

    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"

    REQUIRED_FIELDS = ["email", "first_name", "password"]


    def __str__(self) -> str:
        return "@" + self.username

    def get_profile_picture_url(self):
        """
        Returns the user's profile picture if available; otherwise returns a default image.
        """
        if self.profile_picture and hasattr(self.profile_picture, 'url'):
            return self.profile_picture.url
        return static('gatior/images/default-user-icon.svg')

    def get_full_name(self) -> str:
        return self.first_name + (f" {self.last_name}" if self.last_name else "")
    
NOT_ONLY_WHITESAPCE_REGEX = r'^(?!\s*$).+'

class Post(models.Model):
    user = models.ForeignKey(Account, related_name='posts', on_delete=models.CASCADE)

    image = models.ImageField(
        upload_to='post_images/%Y/%m/%d/',
        blank=False,
        null=False,
        help_text=_('Optional. Upload image for post.'),
    )

    body_validator = RegexValidator(
        regex=NOT_ONLY_WHITESAPCE_REGEX,
        message=_('Text can\'t contain only spaces.')
    )
    body = models.CharField(
        max_length=1200,
        blank=False,
        null=False,
        validators=[body_validator],
    )

    created_at = models.DateTimeField(_("created_at"), default=timezone.now)

    def __str__(self):
        return f"Post #{self.pk} by @{self.user.username}"

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)

    body_validator = RegexValidator(
        regex=NOT_ONLY_WHITESAPCE_REGEX,
        message=_('Text can\'t contain only spaces.')
    )
    body = models.CharField(
        max_length=600,
        blank=False,
        null=False,
        validators=[body_validator],
    )

    created_at = models.DateTimeField(_("created_at"), default=timezone.now)

    def __str__(self):
        return f"Comment #{self.pk} on post #{self.post.pk} by @{self.user.username}"

class Like(models.Model):
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)

    created_at = models.DateTimeField(_("created_at"), default=timezone.now)

    class Meta:
        unique_together = ('post', 'user')

    def __str__(self):
        return f"Like #{self.pk} on post #{self.post.pk} by @{self.user.username}"

accounts/forms.py
# accounts/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Account

class RegisterForm(UserCreationForm):
    """
    Form to register an Account with additional fields.
    """
    class Meta:
        model = Account
        fields = ["first_name", "last_name", "email", "username", "password1", "password2"]

    
    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        user.username = self.cleaned_data["username"]
        if commit:
            user.save()
        return user
    
class LoginForm(forms.Form):
    username = forms.CharField(max_length=Account._meta.get_field("username").max_length)
    password = forms.CharField(widget=forms.PasswordInput)

accounts/views.py
# accounts/views.py

from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.views.generic import CreateView
from django.views.generic.edit import FormView
from django.contrib.auth import login, authenticate, logout
from .forms import RegisterForm, LoginForm

class RegisterView(CreateView):
    """
    View to handle user registration.
    """
    form_class = RegisterForm
    template_name = "accounts/register.html"
    success_url = reverse_lazy("blog:feed")

    def form_valid(self, form):
        user = form.save()
        if user:
            login(self.request, user)  # Correctly log in the user
        return super().form_valid(form)
    
class LoginView(FormView):
    form_class = LoginForm
    template_name = "accounts/login.html"
    success_url = reverse_lazy("blog:feed")

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                return redirect(reverse_lazy("blog:feed"))
        message = 'Login failed!'
        return render(request, self.template_name, context={'form': form, 'message': message})
    

def logout_view(request):
    logout(request)
    return redirect(reverse_lazy("auth:login"))

accounts/templates/accounts/auth_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Gatior Page{% endblock %}</title>
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;700&display=swap" rel="stylesheet">
    <!-- Theme -->
    <link rel="stylesheet" name="color-palette" href="{% static 'gatior/styles/themes/color_palette.css' %}">
    <link rel="stylesheet" id="theme-link" href="{% static 'gatior/styles/themes/light.css' %}">
    <!-- Style -->
    <link rel="stylesheet" name="style" href="{% block personal_style_url %}{% endblock personal_style_url %}">
    <link rel="stylesheet" name="base-style" href="{% static 'gatior/styles/base_style.css' %}">
    <link rel="stylesheet" name="auth-base-style" href="{% static 'gatior/styles/auth_base_style.css' %}">
    <!-- Icons -->
    <link rel="stylesheet" name="icons" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="icon" href="{% static 'gatior/images/attributes/logo-rounded.png' %}">
</head>
<body>
    <!-- Header section -->
    
    <header>
        <nav class="navbar" id="page-header">
            <div class="container">
                <div class="logo">
                    <a href="{% url 'blog:feed' %}">
                        <img src="{% static 'gatior/images/attributes/logo-rounded.png' %}">
                    </a>
                </div>
                <div class="action_container">
                    <div id="theme-icon">
                        <button id="theme-switch-button">
                            <span id="theme-switch-icon" class="material-symbols-outlined">dark_mode</span>
                        </button>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    

    <!-- Main content -->

    <main>
        <div class="main_container">
            <div class="in_page main_column" id="in-page">
                <section id="content">
                    <!-- Django template centent block here -->
                    {% block content %}{% endblock %}
                </section>

                <footer>
                    <hr>
                    <div class="footer-content">
                        <div class="container">
                            <span class="material-symbols-outlined" id="like">memory</span>
                            <span>Site was created to learn web dev</span>
                            <span class="material-symbols-outlined">hub</span>
                        </div>
                    </div>
                </footer>
            </div>
            
            
        </div>
    </main>
    
</body>
{% comment %} <script src="{% static 'gatior/scripts/base.js' %}"></script> {% endcomment %}
<!-- Theme script -->
<script>
// Cant move this script to base.js file because it use django templates for theme path'
var dark_mode = false;

if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    // dark mode
    dark_mode = true;
}
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
    const newColorScheme = event.matches ? "dark" : "light";
});


var theme_switch_button = document.getElementById("theme-switch-button");
var theme_switch_icon = document.getElementById("theme-switch-icon");
theme_switch_button.onclick = switchTheme;
initTheme()

function switchTheme() {
    dark_mode = !dark_mode;
    initTheme();
}
function initTheme() {
    if (dark_mode) {
        // Dark mode
        document.getElementById('theme-link').setAttribute('href', "{% static 'gatior/styles/themes/dark.css' %}");
        theme_switch_icon.innerHTML = "light_mode";
    }
    else {
        // Light mode
        document.getElementById('theme-link').setAttribute('href', "{% static 'gatior/styles/themes/light.css' %}");
        theme_switch_icon.innerHTML = "dark_mode";
    }
}
</script>
{% block personal_script %}{% endblock personal_script %}

</html>

accounts/templates/accounts/login.html
{% extends "accounts/auth_base.html" %}

{% block title %}Gatior Login{% endblock title %}

{% block content %}
{% comment %} <form method="POST"> {% endcomment %}
	{% comment %} {% csrf_token %} {% endcomment %}
	{% comment %} <h2>Login</h2> {% endcomment %}
		{% comment %}  {% endcomment %}
	{% comment %} {% for field in form %} {% endcomment %}
	{% comment %} <p> {% endcomment %}
		{% comment %} {% if field.errors %} {% endcomment %}
		{% comment %} <ul class="errorlist"> {% endcomment %}
			{% comment %} {% for error in field.errors %} {% endcomment %}
			{% comment %} <li>{{ error }}</li> {% endcomment %}
			{% comment %} {% endfor %} {% endcomment %}
		{% comment %} </ul> {% endcomment %}
		{% comment %} {% endif %} {% endcomment %}
	 	{% comment %} {{ field.label_tag }} {{ field }} {% endcomment %}
	{% comment %} </p> {% endcomment %}
	{% comment %} {% endfor %} {% endcomment %}
	{% comment %} <input type="submit" value="Login" /> {% endcomment %}
{% comment %} </form> {% endcomment %}

<div class="content-container">
    <article class="main-area">
        <form method="POST" id="login-form" class="flex-column">
            {% csrf_token %}
            <label class="flex-column" id="username-label" name="username-label">
				<span>Username</span>
				<input type="text" id="username" name="username">
			</label>
			<label class="flex-column" id="password-label" name="password-label">
				<span>Password</span>
				<input type="password" id="password" name="password">
			</label>
            <button id="action-button" type="submit" class="action-button">
                Login
            </button>
			<div class="create-account-field flex-column-centered">
				<span class="secondary">Don't have an account? <a href="{% url 'auth:register' %}">Create one</a></span>
			</div>
		</form>
    </article>
</div>

{% endblock content%}

accounts/templates/accounts/register.html
{% extends "accounts/auth_base.html" %}

{% block title %}Gatior Login{% endblock title %}

{% block content %}
{% comment %} <form method="POST"> {% endcomment %}
	{% comment %} {% csrf_token %} {% endcomment %}
	{% comment %} <h2>Login</h2> {% endcomment %}
		{% comment %}  {% endcomment %}
	{% comment %} {% for field in form %} {% endcomment %}
	{% comment %} <p> {% endcomment %}
		{% comment %} {% if field.errors %} {% endcomment %}
		{% comment %} <ul class="errorlist"> {% endcomment %}
			{% comment %} {% for error in field.errors %} {% endcomment %}
			{% comment %} <li>{{ error }}</li> {% endcomment %}
			{% comment %} {% endfor %} {% endcomment %}
		{% comment %} </ul> {% endcomment %}
		{% comment %} {% endif %} {% endcomment %}
	 	{% comment %} {{ field.label_tag }} {{ field }} {% endcomment %}
	{% comment %} </p> {% endcomment %}
	{% comment %} {% endfor %} {% endcomment %}
	{% comment %} <input type="submit" value="Login" /> {% endcomment %}
{% comment %} </form> {% endcomment %}

<div class="content-container">
    <article class="main-area">
        <form method="POST" id="register-form" class="flex-column">
            {% csrf_token %}
            <label class="flex-column" id="first-name-label" name="first-name-label">
				<span>First Name</span>
				<input type="text" id="first_name" name="first_name">
			</label>
			<label class="flex-column" id="last-name-label" name="last-name-label">
				<span>Last Name</span>
				<input type="text" id="last_name" name="last_name">
			</label>
			<hr>

			<label class="flex-column" id="email-label" name="email-label">
				<span>Email</span>
				<input type="text" id="email" name="email">
			</label>
			<label class="flex-column" id="username-label" name="username-label">
				<span>Username</span>
				<input type="text" id="username" name="username">
			</label>

			<hr>

			<div class="passwords-field">
				<label class="flex-column" id="password1-label" name="password1-label">
					<span>Password</span>
					<input type="password" id="password1" name="password1">
				</label>
				<label class="flex-column" id="password2-label" name="password2-label">
					<span>Confirm password</span>
					<input type="password" id="password2" name="password2">
				</label>
			</div>

			<hr>

            <button id="action-button" type="submit" class="action-button">
                Register
            </button>
			<div class="login-field flex-column-centered">
				<span class="secondary">Already have an account? <a href="{% url 'auth:login' %}">Login into it</a></span>
			</div>
		</form>
    </article>
</div>

{% endblock content%}