accounts/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views
from django.contrib.auth import views as auth_views



app_name = 'auth'

urlpatterns = [
    # path('', RedirectView.as_view(pattern_name='blog:feed', permanent=False), name='redirect-to-feed'),
    # path('feed/', views.FeedView.as_view(), name='feed'),
    # path('post/<int:pk>/', views.PostDetailsView.as_view(), name='post'),
    # path('user/<str:username>/', views.ProfileDetailsView.as_view(), name='user'),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path( "register/", views.RegisterView.as_view(), name='register'),
]

blog/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'blog'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='blog:feed', permanent=False), name='redirect-to-feed'),
    path('feed/', views.FeedView.as_view(), name='feed'),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('post/<int:pk>/', views.PostDetailsView.as_view(), name='post'),
    path('account/<str:username>/', views.ProfileDetailsView.as_view(), name='account'),
    path('account_settings/', views.AccountSettingsView.as_view(), name='account_settings'),
    path('delete_post/<int:pk>', login_required(views.delete_post), name="delete_post"),
    path('delete_comment/<int:pk>', login_required(views.delete_comment), name="delete_comment"),
    path('like_post_button/<int:pk>', login_required(views.like_post_button), name="like_post_button"),
    path('get_post_liked_status/<int:pk>', login_required(views.get_post_liked_status), name="get_post_liked_status"),
]

gatior/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('', lambda request: redirect(reverse_lazy("blog:feed"), permanent=True)),
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("auth/", include("accounts.urls")),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.conf import settings
from django.templatetags.static import static


class Account(AbstractUser):
    username_validator = RegexValidator(
        regex=r'^[a-zA-Z0-9._-]{4,}$',
        message=_('Username can only contain letters, numbers, dots, and underscores.')
    )

    email = models.EmailField(
        _("email address"),
        unique=True,
        blank=False,
        null=False,
        help_text=_('Required. Your email addres.'),
        error_messages={
            'unique': _("A user with that email already exists."),
        },
        )

    username = models.CharField(
        _('username'),
        max_length=20,
        unique=True,
        help_text=_('Required. Your personal identificator. 20 characters or fewer. Letters, numbers, dots, hyphenses and underscores only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    first_name = models.CharField(
        _("first name"),
        max_length=20,
        help_text=_('Required. Your first name you want to be known by.'),
    )
    
    last_name = models.CharField(
        _("last name"),
        max_length=20,
        blank=True,
        help_text=_('Optional. Your last name you want to be known by.'),
    )

    profile_picture = models.ImageField(
        _('profile picture'),
        upload_to='profile_pictures/%Y/%m/%d/',
        blank=True,
        null=True,
        default=None,
        help_text=_('Optional. Upload a profile picture.'),
    )

    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"

    REQUIRED_FIELDS = ["email", "first_name", "password"]


    def __str__(self) -> str:
        return "@" + self.username

    def get_profile_picture_url(self):
        """
        Returns the user's profile picture if available; otherwise returns a default image.
        """
        if self.profile_picture and hasattr(self.profile_picture, 'url'):
            return self.profile_picture.url
        return static('gatior/images/default-user-icon.svg')

    def get_full_name(self) -> str:
        return self.first_name + (f" {self.last_name}" if self.last_name else "")
    
NOT_ONLY_WHITESAPCE_REGEX = r'^(?!\s*$).+'

class Post(models.Model):
    user = models.ForeignKey(Account, related_name='posts', on_delete=models.CASCADE)

    image = models.ImageField(
        upload_to='post_images/%Y/%m/%d/',
        blank=False,
        null=False,
        help_text=_('Optional. Upload image for post.'),
    )

    body_validator = RegexValidator(
        regex=NOT_ONLY_WHITESAPCE_REGEX,
        message=_('Text can\'t contain only spaces.')
    )
    body = models.CharField(
        max_length=1200,
        blank=False,
        null=False,
        validators=[body_validator],
    )

    created_at = models.DateTimeField(_("created_at"), default=timezone.now)

    def __str__(self):
        return f"Post #{self.pk} by @{self.user.username}"

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)

    body_validator = RegexValidator(
        regex=NOT_ONLY_WHITESAPCE_REGEX,
        message=_('Text can\'t contain only spaces.')
    )
    body = models.CharField(
        max_length=600,
        blank=False,
        null=False,
        validators=[body_validator],
    )

    created_at = models.DateTimeField(_("created_at"), default=timezone.now)

    def __str__(self):
        return f"Comment #{self.pk} on post #{self.post.pk} by @{self.user.username}"

class Like(models.Model):
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)

    created_at = models.DateTimeField(_("created_at"), default=timezone.now)

    class Meta:
        unique_together = ('post', 'user')

    def __str__(self):
        return f"Like #{self.pk} on post #{self.post.pk} by @{self.user.username}"

blog/models.py
from django.db import models

# Create your models here.

accounts/forms.py
# accounts/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Account

class RegisterForm(UserCreationForm):
    """
    Form to register an Account with additional fields.
    """
    class Meta:
        model = Account
        fields = ["first_name", "last_name", "email", "username", "password1", "password2"]

    
    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        user.username = self.cleaned_data["username"]
        if commit:
            user.save()
        return user
    
class LoginForm(forms.Form):
    username = forms.CharField(max_length=Account._meta.get_field("username").max_length)
    password = forms.CharField(widget=forms.PasswordInput)

blog/forms.py
# accounts/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import Comment, Post, Account  
    
class CreatePostForm(forms.Form):
    image = forms.ImageField(required=True)
    body = forms.CharField(
        max_length=Post._meta.get_field("body").max_length,
        widget=forms.Textarea(attrs={'rows': 8, 'cols': 40}),
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        post = Post()
        post.body = self.cleaned_data["body"]
        post.user = self.user

        if self.cleaned_data["image"]:
            post.image = self.cleaned_data["image"]

        if commit:
            post.save()
        return post



class CreateCommentForm(forms.Form):
    body = forms.CharField(
        max_length=Comment._meta.get_field("body").max_length,
        widget=forms.Textarea(attrs={'rows': 8, 'cols': 40}),
        )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.post = kwargs.pop('post', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = Comment

    def save(self, commit=True):
        comment = Comment()
        comment.body = self.cleaned_data["body"]
        comment.user = self.user
        comment.post = self.post

        # user.first_name = self.cleaned_data["first_name"]
        # user.last_name = self.cleaned_data["last_name"]
        # user.email = self.cleaned_data["email"]
        # user.username = self.cleaned_data["username"]
        # user.password = self.cleaned_data["password"]
        if commit:
            comment.save()

        return comment
    
class AccountSettingsForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["profile_picture", "first_name", "last_name"]


    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        account = self.user

        print(self.cleaned_data)

        if len(self.cleaned_data["first_name"]) > 0: 
            account.first_name = self.cleaned_data["first_name"]

        account.last_name = self.cleaned_data["last_name"]

        if self.cleaned_data["profile_picture"]:
            account.profile_picture = self.cleaned_data["profile_picture"]

        if commit:
            account.save()
        return account
    
    

accounts/views.py
# accounts/views.py

from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.views.generic import CreateView
from django.views.generic.edit import FormView
from django.contrib.auth import login, authenticate, logout
from .forms import RegisterForm, LoginForm

class RegisterView(CreateView):
    """
    View to handle user registration.
    """
    form_class = RegisterForm
    template_name = "accounts/register.html"
    success_url = reverse_lazy("blog:feed")

    def form_valid(self, form):
        user = form.save()
        if user:
            login(self.request, user)  # Correctly log in the user
        return super().form_valid(form)
    
class LoginView(FormView):
    form_class = LoginForm
    template_name = "accounts/login.html"
    success_url = reverse_lazy("blog:feed")

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                return redirect(reverse_lazy("blog:feed"))
        message = 'Login failed!'
        return render(request, self.template_name, context={'form': form, 'message': message})
    

def logout_view(request):
    logout(request)
    return redirect(reverse_lazy("auth:login"))

blog/views.py
from typing import Any
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.db.models import Count
from accounts.models import Post, Comment, Account, Like
from .forms import CreatePostForm, CreateCommentForm, AccountSettingsForm

class FeedView(generic.ListView):
    model = Post
    template_name = "blog/feed.html"
    context_object_name = "posts"
    paginate_by = 20
    login_required = True

    ordering = ["-created_at",]

    def get_context_data(self, **kwargs):
        # Add any extra context needed in the template
        context = super().get_context_data(**kwargs)

        context["posts"] = Post.objects.get_queryset().annotate(
            likes_count=Count("likes", distinct=True),
            comments_count=Count('comments', distinct=True),
        ).order_by(*self.ordering)

        return context

class PostDetailsView(generic.DetailView, generic.FormView):
    model = Post
    template_name = "blog/post.html"
    context_object_name = "post"

    form_class = CreateCommentForm
    success_url = reverse_lazy("blog:feed")

    login_required = True

    def get_context_data(self, **kwargs):
        # Add any extra context needed in the template
        context = super().get_context_data(**kwargs)

        context['comments'] = Comment.objects.filter(post=context["post"]).order_by("-created_at")

        current_post_likes = Like.objects.get_queryset().filter(post=context["post"])
        context["like_count"] = current_post_likes.count()
        context["is_liked"] = current_post_likes.filter(user=self.request.user).exists()

        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(request.POST, user=request.user, post=self.object)  # Pass the user
        message = None
        if form.is_valid():
            comment = form.save()
            if comment is None:
                message = 'There is an error when publishing your comment'
            else:
                form = self.form_class(user=request.user, post=self.object)
        else:
            message = 'There is an error when publishing your comment'


        return self.render_to_response(self.get_context_data(form=form, message=message))
    
class ProfileDetailsView(generic.DetailView):
    model = Account
    template_name = "blog/account.html"
    context_object_name = "account"
    login_required = True

    def get_object(self):
        # Retrieve the user by username
        username = self.kwargs.get('username')
        return get_object_or_404(Account, username=username)
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context["posts"] = Post.objects.filter(user=context["account"]).annotate(
            likes_count=Count("likes", distinct=True),
            comments_count=Count('comments', distinct=True),
        ).order_by("-created_at")
        # print(context["posts"][0].body[:10], context["posts"][0].likes_count)

        return context

    
class CreatePostView(generic.FormView):
    form_class = CreatePostForm
    template_name = "blog/create_post.html"
    success_url = reverse_lazy("blog:feed")
    login_required = True

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES, user=request.user)  # Pass the user
        if form.is_valid():
            post = form.save()
            return redirect(self.success_url)
        
        # If form is invalid, re-render the page with the form data and error messages
        return self.form_invalid(form)

    def form_invalid(self, form):
        print(form.errors)
        return HttpResponse(f'{form.errors}')

class AccountSettingsView(generic.FormView):
    form_class = AccountSettingsForm
    template_name = "blog/account_settings.html"
    login_required = True

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES, user=request.user)  # Pass the user
        if form.is_valid():
            account = form.save()
            return redirect(reverse_lazy("blog:account", kwargs={'username': request.user.username}))
        
        # If form is invalid, re-render the page with the form data and error messages
        return self.form_invalid(form)

    def form_invalid(self, form):
        print(form.errors)
        return HttpResponse(f'{form.errors}')


def delete_post(request, pk):
    post = Post.objects.get(pk=pk)
    if post.user == request.user:
        post.delete()
    return redirect(reverse_lazy("blog:account", kwargs={'username': request.user.username}))

def delete_comment(request, pk):
    comment = Comment.objects.get(pk=pk)
    if comment.user == request.user:
        comment.delete()

    return redirect(request.META.get('HTTP_REFERER', '/')) 
    # return redirect(reverse_lazy("blog:account", kwargs={'username': request.user.username}))

def like_post_button(request, pk):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        post = Post.objects.get(pk=pk)

        like, created = Like.objects.get_or_create(post=post, user=request.user)

        if not created:
            like.delete()


        return get_post_liked_status(request, pk)
    return redirect(reverse_lazy("blog:feed"))

def get_post_liked_status(request, pk):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        post = Post.objects.get(pk=pk)

        post_likes = Like.objects.filter(post=post)

        liked_by_user = post_likes.filter(user=request.user).exists()

        data = {
            "liked_by_user": liked_by_user,
            "like_count": post_likes.count(),
        }

        return JsonResponse(data, status=200)
    return redirect(reverse_lazy("blog:feed"))

blog/templates/blog/account.html
{% extends "gatior/base.html" %}

{% load static %}

{% block title %}User Detail{% endblock title %}

{% block personal_style_url %}{% static 'gatior/styles/account_style.css' %}{% endblock personal_style_url %}


{% block content %}
<!-- Django template centent block here -->
<header class="profile-header">
    <div class="profile-header-container">
        <img id="profile-picture" src="{{ account.get_profile_picture_url }}">
        <div class="profile-info-container">
            <div class="main-profile-info">
                <span id="profile-name">{{ account.get_full_name }}</span>
                <span id="profile-username">@{{ account.username }}</span>
                <span id="profile-joined">Joined: {{ account.date_joined }}</span>
            </div>
            <span id="profile-post-count">{{ posts|length }} posts</span>
        </div>
        <div class="settings-area">
            <a href="{% url 'blog:account_settings' %}">
                <span class="material-symbols-outlined">
                    settings
                </span>
            </a>
        </div>
    </div>
</header>
<div class="profile-body">
    <div class="profile-posts-container-pseudo">
        <hr>
        <div class="profile-posts-container">
            {% for post in posts %}
                <article class="profile-post" style="background-image: url({{ post.image.url }});">
                    <a href="{% url 'blog:post' post.pk %}">
                        <div class="hide-square">
                            <div class="post-info">
                                <span class="post-info-icon">{{post.likes_count}} <span class="material-symbols-outlined">favorite</span></span>
                                <span class="post-info-icon">{{post.comments_count}} <span class="material-symbols-outlined">chat_bubble</span></span>
                            </div>
                        </div>
                    </a>
                </article>
            {% endfor %}
            
        </div>
    </div>
</div>
 
{% endblock content %}

blog/templates/blog/account_settings.html
{% extends "gatior/base.html" %}
{% load static %}

{% block title %}Edit account info{% endblock title %}

{% block personal_style_url %}{% static 'gatior/styles/account_settings_style.css' %}{% endblock personal_style_url %}


{% block content %}
<div class="content-container">
    <article class="account">
        <form method="POST" id="form" class="flex-column" enctype="multipart/form-data">
            {% csrf_token %}
            <label class="account-image-container" name="image" id="account-image-container" style="background-image: url({{ user.get_profile_picture_url }});">
                <input type="file" accept="image/*" id="upload-image" name="profile_picture">
                {% if user.profile_picture == None or user.profile_picture == null %}
                    <span id="select-image-text">Select image</span>
                {% endif %}
            </label>
            
            <label class="flex-column" id="first-name-label" name="first-name-label">
				<span>First name</span>
				<input type="text" id="first_name" name="first_name" value="{{ user.first_name }}">
			</label>
            <label class="flex-column" id="last-name-label" name="last-name-label">
				<span>Last name</span>
				<input type="text" id="last_name" name="last_name" value="{{ user.last_name }}">
			</label>
            <button id="save-button" type="submit" class="save-button">
                Save
            </button>
        </form>
    </article>
</div>
{% endblock content %}

{% block personal_script %}
<script src="{% static 'gatior/scripts/account_settings_page.js' %}"></script>
<script>
</script>
{% endblock personal_script %}

blog/templates/blog/post.html
{% extends "gatior/base.html" %}
{% load static %}

{% block title %}Post Detail{% endblock title %}

{% block personal_style_url %}{% static 'gatior/styles/post_style.css' %}{% endblock personal_style_url %}


{% block content %}
<div class="content-container">
    <section class="post-section" id="post-section">
        <article class="post-container" id="post-container">
            <header class="post-header">
                <a class="author-info flex-row" href="{% url 'blog:account' post.user.username %}">
                    <img class="author-icon" src="{{ post.user.get_profile_picture_url }}">
                    <div class="post-header-text flex-column">
                        <span class="author-name">{{ post.user.get_full_name }}</span>
                        <span class="post-date secondary">{{ post.created_at }}</span>
                    </div>
                </a>
                {% if post.user == user %}
                    <button class="delete-button" id="delete-post-button" onclick="deletePost()">
                        <span class="material-symbols-outlined">delete</span>
                    </button>
                {% endif %}
            </header>
            <div class="image-container" id="post-image-container">
                <button id="post-image-button">
                    <img class="post-image" id="post-image" src="{{ post.image.url }}">
                </button>
            </div>
            <div class="post-footer">
                <div class="post-likes flex-row">
                    <button id="like-post-button" class="like-button flex-row-centered">
                        <span id="post-like-count">{{ like_count }}</span>
                        <span id="like-post-icon" class="material-symbols-outlined">favorite</span>
                    </button>
                </div>
            </div>
            <p class="post-body">
                {{ post.body|linebreaksbr }}
            </p>
        </article>
    </section>
    <section class="comments-section" id="comments-section">
        <div class="comments-container flex-column" id="comment-container">
            <section class="write-comment flex-row">
                <textarea id="write-comment-field" rows="5" placeholder="Write comment..."></textarea>
                <button id="write-comment-button" type="submit" class="write-comment-button">
                    <span class="material-symbols-outlined">send</span>
                </button>
            </section>
            <div id="comment-list" class="flex-column">
                {% for comment in comments %}
                    <article class="comment flex-column" id="comment-{{ comment.pk }}">
                        <header class="comment-header">
                            <div class="comment-info flex-row">
                                <a class="flex-row" href="{% url 'blog:account' comment.user.username %}">
                                    <img class="author-icon" src="{{ comment.user.get_profile_picture_url }}">
                                    <div class="comment-info-text flex-column">
                                        <span>{{ comment.user.get_full_name }}</span>
                                        <span class="comment-date secondary">{{ comment.created_at }}</span>
                                    </div>
                                </a>
                            </div>
                            {% if comment.user.pk == user.pk %}
                                <button class="delete-button" id="delete-comment-{{ comment.pk }}"  onclick="deleteComment({{ comment.pk }})">
                                    <span class="material-symbols-outlined">delete</span>
                                </button>
                            {% endif %}
                        </header>
                        <p class="comment-body">
                            {{ comment.body|linebreaksbr }}
                        </p>
                    </article>            
                {% endfor %}
            </div>
        </div>
    </section>
</div>
{% endblock content %}

{% block personal_script %}
<script src="{% static 'gatior/scripts/post_page.js' %}"></script>
<script>

var like_post_button = document.getElementById("like-post-button");
var like_post_icon = document.getElementById("like-post-icon");
var post_like_count = document.getElementById("post-like-count");  

like_post_button.onclick = function() {

    fetch("{% url 'blog:like_post_button' post.pk %}", {
        method: 'POST',
        credentials: 'same-origin',
        headers:{
            'Accept': 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
            'X-CSRFToken': csrftoken,
        },
        body: JSON.stringify({})
    })
    .then(response => {
        if (!response.ok) {
            throw new Error(`HTTP error: ${response.status}`);
        }
        return response.json();
    })
    .then(data => {
        initPostLikeHTML(data.liked_by_user, data.like_count);
    })
    .then(function() {
        chatSocket.send(create_message(""));
    })
}


function initPostLikeHTML(liked_by_user, like_count) {
    if (liked_by_user) {
        if (!like_post_button.classList.contains("like-button-filled") && !like_post_button.classList.contains("like-button")) {
            like_post_button.classList.add("like-button-filled");
        }
        else {
            like_post_button.classList.replace("like-button", "like-button-filled");
        }
    } 
    else {
        if (!like_post_button.classList.contains("like-button-filled") && !like_post_button.classList.contains("like-button")) {
            like_post_button.classList.add("like-button");
        }
        else {
            like_post_button.classList.replace("like-button-filled", "like-button");
        }
        
    };
    post_like_count.innerHTML = like_count;
}

initPostLike();

// Yep, this funtion repeat a lot from "like_post_button.onclick"
function initPostLike() {
    fetch("{% url 'blog:get_post_liked_status' post.pk %}", {
        method: 'GET',
        credentials: 'same-origin',
        headers:{
            'Accept': 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
            'X-CSRFToken': csrftoken,
        },
    })
    .then(response => {
        if (!response.ok) {
            throw new Error(`HTTP error: ${response.status}`);
        }
        return response.json();
    })
    .then(data => {
        initPostLikeHTML(data.liked_by_user, data.like_count)
    });
}

// ------------- Sockets -------------
const postRoomID = JSON.parse({{ post.pk }});

const chatSocket = new WebSocket(
    'ws://'
    + window.location.host
    + '/ws/post/'
    + postRoomID
    + '/'
);



// Get WebSocket message from Server
chatSocket.onmessage = function(e) {
    const data = JSON.parse(e.data);
    if (data.delete_post) {
        window.location.replace("{% url 'blog:feed' %}");
    }
    if (data.comment.body.length > 0) {
        addComment(data)
    }
    if (data.delete_pk.length > 0) {
        comment_to_delete = document.getElementById(`comment-${data.delete_pk}`);
        if (comment_to_delete != null) { 
            comment_to_delete.remove();
        }
    }
    post_like_count.innerHTML = data.like_count
};

// Error handling
chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
};

write_comment_button = document.getElementById('write-comment-button');

// Publidh comment and send WebSocket
write_comment_button.onclick = function(e) {
    const writeCommentField = document.getElementById('write-comment-field');
    chatSocket.send(create_message(writeCommentField.value));
    writeCommentField.value = '';
};

let comment_list = document.getElementById("comment-list")

// Create comment HTML element
function addComment(data) {
    comment = data.comment;

    let delete_button_html = ""
    if (comment.user_pk == {{ user.pk }}) {
        delete_button_html = `
            <button class="delete-button" id="delete-comment-${comment.pk}" onclick="deleteComment(${ comment.pk })">
                <span class="material-symbols-outlined">delete</span>
            </button>
        `
    }


    comment_list.innerHTML = `
    <article class="comment flex-column" id="comment-${comment.pk}">
        <header class="comment-header">
            <div class="comment-info flex-row">
                <a class="flex-row" href="${comment.authors_url}">
                    <img class="author-icon" src="${comment.authors_icon_url}">
                    <div class="comment-info-text flex-column">
                        <span>${comment.authors_full_name}</span>
                        <span class="comment-date secondary">${comment.created_at}</span>
                    </div>
                </a>
            </div>
            ${delete_button_html}
        </header>
        <p class="comment-body">
            ${comment.body}
        </p>
    </article>   
    ` + comment_list.innerHTML;
    // After adding comment link to button clears, so we need to relink it
    write_comment_button = document.getElementById('write-comment-button');
}

function deleteComment(pk) {
    chatSocket.send(create_message("", pk.toString()));
}

function deletePost() {
    chatSocket.send(create_message("", "", true));
}

function create_message(comment_body="", delete_pk="", delete_post=false) {
    let message = new Object(); 
    message.post_pk = {{ post.pk }};
    message.user_pk = {{ user.pk }};

    comment = new Object();

    comment.body = comment_body;
    comment.user_pk = {{ user.pk }};
    comment.authors_url = "{% url 'blog:account' user.username %}";
    comment.authors_icon_url = "{{ user.get_profile_picture_url }}";
    comment.authors_full_name = "{{ user.get_full_name }}";
    comment.created_at = "";
    comment.pk = "";

    message.comment = comment;

    message.delete_pk = delete_pk;
    message.delete_post = delete_post;

    return JSON.stringify(message);
}



</script>
{% endblock personal_script %}