accounts/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views
from django.contrib.auth import views as auth_views



app_name = 'auth'

urlpatterns = [
    # path('', RedirectView.as_view(pattern_name='blog:feed', permanent=False), name='redirect-to-feed'),
    # path('feed/', views.FeedView.as_view(), name='feed'),
    # path('post/<int:pk>/', views.PostDetailsView.as_view(), name='post'),
    # path('user/<str:username>/', views.ProfileDetailsView.as_view(), name='user'),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path( "register/", views.RegisterView.as_view(), name='register'),
]

blog/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'blog'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='blog:feed', permanent=False), name='redirect-to-feed'),
    path('feed/', views.FeedView.as_view(), name='feed'),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('post/<int:pk>/', views.PostDetailsView.as_view(), name='post'),
    path('account/<str:username>/', views.ProfileDetailsView.as_view(), name='account'),
    path('account_settings/', views.AccountSettingsView.as_view(), name='account_settings'),
    path('delete_post/<int:pk>', login_required(views.delete_post), name="delete_post"),
    path('delete_comment/<int:pk>', login_required(views.delete_comment), name="delete_comment"),
    path('like_post_button/<int:pk>', login_required(views.like_post_button), name="like_post_button"),
    path('get_post_liked_status/<int:pk>', login_required(views.get_post_liked_status), name="get_post_liked_status"),
]

gatior/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('', lambda request: redirect(reverse_lazy("blog:feed"), permanent=True)),
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("auth/", include("accounts.urls")),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gatior/templates/gatior/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Gatior Page{% endblock %}</title>
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;700&display=swap" rel="stylesheet">
    <!-- Theme -->
    <link rel="stylesheet" name="color-palette" href="{% static 'gatior/styles/themes/color_palette.css' %}">
    <link rel="stylesheet" id="theme-link" href="{% static 'gatior/styles/themes/light.css' %}">
    <!-- Style -->
    <link rel="stylesheet" name="style" href="{% block personal_style_url %}{% endblock personal_style_url %}">
    <link rel="stylesheet" name="base-style" href="{% static 'gatior/styles/base_style.css' %}">
    <!-- Icons -->
    <link rel="stylesheet" name="icons" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="icon" href="{% static 'gatior/images/attributes/logo-rounded.png' %}">
</head>
<body>
    <!-- Header section -->
    
    <header>
        <nav class="navbar" id="page-header">
            <div class="container">
                <div class="logo">
                    <a href="{% url 'blog:feed' %}">
                        <img src="{% static 'gatior/images/attributes/logo-rounded.png' %}">
                    </a>
                </div>
                <div class="action_container">
                    <div id="search-icon">
                        <a href="{% url 'blog:feed' %}">
                            <span class="material-symbols-outlined">search</span>
                        </a>
                    </div>
                    <div id="theme-icon">
                        <button id="theme-switch-button">
                            <span id="theme-switch-icon" class="material-symbols-outlined">dark_mode</span>
                        </button>
                    </div>
                    <div id="profile-icon">
                        <a href="{% url 'blog:account' user.username %}">
                            <img src="{{ user.get_profile_picture_url }}">
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    

    <!-- Main content -->

    <main>
        <div class="main_container">
            <aside class="sidenav main_column" id="main-side_panel">
                <button class="collapse" id="collapse-side-panel">
                    <span class="material-symbols-outlined" id="collapse-side-panel-arrow"><!-- CSS insert arrows here --></span>
                </button>
                <div class="container">
                    <div class="side-panel-elements-container" id="side-panel-content">
                        <a href="{% url 'blog:account' user.username %}">
                            <div class="sidenav_element">
                                <span class="material-symbols-outlined">account_circle</span>
                                <span>Profile</span>
                            </div>
                        </a>
                        <a href="{% url 'blog:create_post' %}">
                            <div class="sidenav_element">
                                <span class="material-symbols-outlined">add_circle</span>
                                <span>Create Post</span>
                            </div>
                        </a>
                        <a href="{% url 'blog:feed' %}">
                            <div class="sidenav_element">
                                <span class="material-symbols-outlined">list_alt</span>
                                <span>Feed</span>
                            </div>
                        </a>
                        <a href="{% url 'auth:logout' %}">
                            <div class="sidenav_element">
                                <span class="material-symbols-outlined">logout</span>
                                <span>Logout</span>
                            </div>
                        </a>
                        <a href="{% url 'auth:login' %}">
                            <div class="sidenav_element">
                                <span class="material-symbols-outlined">login</span>
                                <span>Login</span>
                            </div>
                        </a>
                    </div>
                </div>
            </aside>
            <div class="in_page main_column" id="in-page">
                <section id="content">
                    <!-- Django template centent block here -->
                    {% block content %}{% endblock %}
                </section>

                <footer>
                    <hr>
                    <div class="footer-content">
                        <div class="container">
                            <span class="material-symbols-outlined" id="like">memory</span>
                            <span>Site was created to learn web dev</span>
                            <span class="material-symbols-outlined">hub</span>
                        </div>
                    </div>
                </footer>
            </div>
            
            
        </div>
    </main>
    
</body>
<script src="{% static 'gatior/scripts/base.js' %}"></script>
<!-- Theme script -->
<script>
    // Cant move this script to base.js file because it use django templates for theme path'
    
    var dark_mode = true;

    var theme_switch_button = document.getElementById("theme-switch-button");
    var theme_switch_icon = document.getElementById("theme-switch-icon");
    theme_switch_button.onclick = switchTheme;

    initTheme()

    

    function switchTheme() {
        dark_mode = !dark_mode;
        initTheme();
    }


    function initTheme() {
        if (dark_mode) {
            // Dark mode
            document.getElementById('theme-link').setAttribute('href', "{% static 'gatior/styles/themes/dark.css' %}");
            theme_switch_icon.innerHTML = "light_mode";
        }
        else {
            // Light mode
            document.getElementById('theme-link').setAttribute('href', "{% static 'gatior/styles/themes/light.css' %}");
            theme_switch_icon.innerHTML = "dark_mode";

        }
    }
</script>
{% block personal_script %}{% endblock personal_script %}

</html>